name: exception_handler
description: A Dart package for streamlined API handling and robust exception management in Flutter apps.
version: 3.0.0
homepage: "https://github.com/andgar2010/exception_handler"

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.19.0"

dependencies:
  connectivity_plus: ^6.0.1
  dio: ^5.4.2
  equatable: ^2.0.5
  http_exception: ^2.0.0
  flutter:
    sdk: flutter
  http_status: ^3.3.0

dev_dependencies:
  dart_code_linter:
    git:
      url: https://github.com/andgar2010/dart-code-linter/
      ref: fix_analyzer_6_0
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mocktail: ^1.0.3
  flutter_coverage_badge:
    git:
      url: https://github.com/foresightmobile/flutter_coverage_badge
      ref: 4d6371f1bd46fee1bd28a697e303412839e53548

screenshots:
  - description: 'Examples of the exception_handler on Windows.'
    path: exception_handler_demo.gif

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
