name: "exception_handler"

on: # rebuild any PRs and main branch changes
  pull_request:
    # branches: [ master ]
  push:
    branches:
      - main # [ master ]

jobs:
  # Check code formatting and static analysis on a single OS (linux)
  # against Dart dev.
  test:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest] # or: macos-latest, windows-latest
        channel: [stable] # or: 'beta', 'dev' or 'master'
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ matrix.channel }}

      - id: disabled_analytics_flutter
        name: Disabled Analytics Flutter
        run: flutter config --no-analytics

      - id: disabled_analytics_dart
        name: Disabled Analytics Dart
        run: dart --disable-analytics

      - id: checking_version_flutter
        name: Check version Flutter is installed
        run: flutter --version

      - id: install_dependencies
        name: Install dependencies
        run: flutter pub get

      - name: Check formatting
        run: dart format --output=none --set-exit-if-changed .
        # if: always() && steps.install.outcome == 'success'

      - name: Analyze code
        run: dart analyze --fatal-infos
        # if: always() && steps.install.outcome == 'success'

      - id: install_very_good_cli
        name: Install Very Good CLI
        run: dart pub global activate very_good_cli

      - name: Run tests with coverage
        run: very_good test --coverage
        # if: always() && steps.install.outcome == 'success'

      - name: Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v2
        with:
          path: "./coverage/lcov.info"
          min_coverage: 98

      - id: run_package_flutter_coverage_badge
        name: Run package flutter_coverage_badge
        run: flutter pub run flutter_coverage_badge

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Andrés García
          author_email: dev@tech-andgar.me
          message: 'Updated coverage_badge.svg'
          add: 'coverage_badge.svg'

      - name: Upload Coveralls coverage
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage/lcov.info
