name: Publish to pub.dev

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*' # for tags like: '1.2.3'

jobs:
  publish:
    environment: pub.dev
    permissions:
      id-token: write # This is required for requesting the JWT
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - uses: actions/checkout@v4
      # Setup Flutter SDK
      - uses: subosito/flutter-action@v2
      # Minimal package setup and dry run checks.
      - name: Install dependencies
        run: flutter pub get
      - name: Publish - dry run
        run: dart pub publish --dry-run
      # Publishing...
      - name: Publish to pub.dev
        run: dart pub publish -f
